version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  nextjs:
    lang: dockerfile
    handler: ./nextjs
    image: wilsonianbcoil/nextjs-demo:latest
    environment:
      write_debug: true
